[project]
name = "books"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.15.1",
    "litestar>=2.15.1",
    "psycopg2-binary>=2.9.10",
    "pydantic-settings>=2.8.1",
    "uvicorn>=0.34.0",
]
