"""add user role and is_activate status

Revision ID: 8f55b23c6b3f
Revises: 1481f515c9bf
Create Date: 2025-04-08 10:52:36.326487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f55b23c6b3f'
down_revision: Union[str, None] = '1481f515c9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

user_role_enum = sa.Enum('banner', 'user', 'admin', name='userrole')

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    user_role_enum.create(op.get_bind())

    op.add_column(
        'users',
        sa.Column('role', user_role_enum, nullable=False, server_default=sa.text("'user'"))
    )

    op.add_column(
        'users',
        sa.Column('is_activate', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('users', 'is_activate')
    user_role_enum.drop(op.get_bind())
    # ### end Alembic commands ###
